### ISSUE TITLE
when I run node bin/www, nothing happens

### ISSUE THREAD

**Issue by andreichch** [sushantshekhar20/bot_api.ai#1]
Hi Sushant,

Thanks very much for your tutorial/article on Chatbotslife and the project. I have:

- cloned the repo
- run npm install
- modified the api.js file (and verified that I get results from my api.ai agent)

when I run node bin/www, nothing happens - nothing appears in the CMD screen or anywhere else

I think I am missing something both important and simple; please let me know what that might be.

Thanks,
Andrei Link

**Comment by sheksushant** [comment]
Thanks for pointing it out, I forgot to write the traditional line "server running at 3000".
Its fixed now, **use git pull and it should work now.**
**or** just go to localhost:300 in your browser from your previous cloned repo.

**Comment by andreichch** [comment]
Thank you very much, it is working now!
