### ISSUE TITLE
Fix suggested in sock.js

### ISSUE THREAD

**Issue by andreichch** [sushantshekhar20/bot_api.ai#2]
Hi Shushant,

I believe a fix may be needed in sock.js: on line 20 we have:

api.getRes('hello').then(function(res){

I could only get the bot to show me correct responses from APIAI when I changed this line to:

api.getRes(data.client).then(function(res){

Also, I don't know why, but when I get the first correct response in the browser, I don't see a prompt/field to enter the next questions. I played with the code in convo.js but could not make it work. 

Thanks again,
Andrei

**Comment by sheksushant** [comment]
Thank you for the suggestion! I have fixed it.

**Comment by andreichch** [comment]
sure, thank you.

have you been able to reproduce this: "Also, I don't know why, but when I get the first correct response in the browser, I don't see a prompt/field to enter the next questions." ?

**Comment by andreichch** [comment]
oh, and i just noticed i had misspellt your name, sorry about this.

**Comment by sheksushant** [comment]
I have only configured it for some messages, you can go and read docs of BotUI https://docs.botui.org . BotUI is the UI framework used for this repo. read about .then() function.
