### ISSUE TITLE
Error: ERR_CONNECTION_REFUSED on socket.io

### ISSUE THREAD

**Issue by Poorav** [sushantshekhar20/bot_api.ai#4]
I follow the step as show in your blog.
seems like everything works but after the first message 'Hello'
input box goes away and nothing happens.
I'm not able to figure out this problem.
and in console gives error like:
**GET http://localhost:8010/socket.io/?EIO=3&transport=polling&t=LxgVYPO net::ERR_CONNECTION_REFUSED  at polling-xhr.js:264**

**Comment by Kaushikdugar** [comment]
I am also having the same issue.Any help would be great

**Comment by Axelest** [comment]
any updates on this?

**Comment by HamzaFarhan** [comment]
any updates?

**Comment by kimdj** [comment]
RIP.

**Comment by Axelest** [comment]
What is the error you are still seeing?

**Comment by kimdj** [comment]
No error; but I enter in 'hello' and no response.

**Comment by ghost** [comment]
@kimdj Did you enter your API key in `config/api.js`?

**Comment by ghost** [comment]
@Poorav, @Kaushikdugar,

If you get errors, Try cloning this repo for usage.

I noticed some errors in the blog but I can't fix them as I did not write it.

@sushantshekhar20 Kindly check the code used in the blog once again

**Comment by Axelest** [comment]
The blog is not complete, it never tells you how to setup your server and extend it with the web socket. I had to read the code behind and got it to work. If you want to avoid this then just clone the repo but again you won’t be able to understand any issue if anything happens. If no error occurs and no response happens then you might try to login into the service dashboard to configure your bot. You are also available to tray it from there if it works fine there it should work fine in your app.

**Comment by kimdj** [comment]
@clemtrek Yes; I used the client access token.  I can get to the "Let's start talking..." prompt, but it doesn't do anything after I enter something in.

**Comment by ghost** [comment]
@kimdj Try cloning this repo and then doing the same thing.

**Comment by NikeshMewada** [comment]
@Poorav, @Kaushikdugar,

Two things to make this work:
1. Make sure your 'api.js' and 'sock.js' are in 'config' folder
2. Copy and Paste the below code in 'app.js'

var socket = require('./config/sock');
socket.conn();
socket.fromClient();

This is solve the error.
Thanks :)

**Comment by uadp** [comment]
IMO,

it not code problem, you can change localhost with your IP address.
e.g 127.0.0.1 if you running this script in local computer.

remember convo.js is running on client machine so, make it correct connection.

FYI, i'm running this script on VPS, so i change localhost with public IP addresss. and everything running without problem.
