### ISSUE TITLE
Issue while executing the chatbotui tutorials

### ISSUE THREAD

**Issue by shrinidhi-ha** [sushantshekhar20/bot_api.ai#7]
Following this link:
https://chatbotslife.com/custom-api-ai-chatbot-using-botui-58d673155c7d

**Issues are:**
1. There are many js files which are created in separate folders but where does that folders exist or does this folder need to be created manually?
2. why does express module after following the instruction not able recognize the command
express --view=ejs my_cool_bot view is not executed getting this error
**C:\Users\shrinidhi_ha\Documents\chatbotui>express --view=ejs my_cool_bot view
'express' is not recognized as an internal or external command,**
operable program or batch file.

3. why node bin/www throw this error
module.js:545
    throw err;
    ^

Error: Cannot find module 'C:\Users\shrinidhi_ha\Documents\chatbotui\bin\www'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
4. Go to public/javascripts and create a new file and name it convo.js what does this mean? where should we look out for public/javascripts folder?

directory structure in C Drive Documents of my system
![image](https://user-images.githubusercontent.com/37453552/37536988-368cf4d6-2972-11e8-92af-742f3901876a.png)
please help me out in resolving the issue as i am a new comer to botui development. I am from a background java, javascript development but unable to trace out this issue. 
enclosing the js files and package.json file created for chatbotui program.

[chatbotui.zip](https://github.com/sushantshek20/bot-dialogflow/files/1820325/chatbotui.zip)

**Comment by sudhir512kj** [comment]
@shrinidhi-ha 
Here are some solutions to your problems:
<ol start="1">
  <li>There is a folder <b>Javacsripts</b> in <b>public folder</b>, There you can put your <b>convo.js</b> file.</li>
  <li>You have not installed <b>express-generator</b>.</li>
  <li>There is a folder seeing in your screenshot named <b>public</b>.</li>
</ol>
