### ISSUE TITLE
SessionID with Dialogflow

### ISSUE THREAD

**Issue by in-flu-ence** [sushantshekhar20/bot_api.ai#9]
All installation is good and I can communicate successfully with Dialogflow. However, I notice that it is under 1 single dialog regardless of the browser that I would use. This can be quite a security issue since multiple users are speaking using a single session ID. What should be the modification so that the ID can be assigned to different users (e.g. different browser, ip address) or different session once browser is closed?

**Comment by in-flu-ence** [comment]
I resolved my own issue. Refer to socket.io to define your own sessionId code to replace that in api.js.

**Comment by Fachastorm** [comment]
Hello, 

I seem to be having the same issue here with Dialogflow and I was wondering if you could show me how it is that you fixed this issue? Thank you!
